FROM gitpod/workspace-python-tk-vnc
RUN sudo apt-get update && \
    sudo apt-get install -y libgtk-3-dev && \
    sudo rm -rf /var/lib/apt/lists/* && \
    sudo apt-get update &&\
    sudo apt-get install python3-tk 